### ISSUE TITLE
HELP-> dll's for windows 8

### ISSUE THREAD

**Issue by carlos-augusto-prt** [BoutemineOualid/WfdbCsharpWrapper#1]
This solution doesn't work on windows 8 x64. I'm not sure why, but I think the problem is in wfdb.dll file in package folder or WfdbCsharpLib.dll in Binary folder.

I don't know how to make the native windows 8 version of the necessary files, and integrate them into the project.

can someone help me?

**Comment by BoutemineOualid** [comment]
Hi,
Thanks for your feedback.

The library was tested on windows 8/8.1/10 both 32 and 64 platforms and it works fine. The native wfdb dll file being wrapped was however built targeting the 32bit platform. You just need to make sure that the target platform of the wrapper solution is x86 in Visual Studio's configuration manager. This would allow ms build to produce a standard PE32/x86 executable which the OS can correctly load along with the CLR in a WoW64 address space.

Let me know if this helps,
Regards,
Oualid

**Comment by carlos-augusto-prt** [comment]
thank you Oualid, the solution is working now.

just a summary for everyone. you just need to do the follow steps:

.Solution 'wfdbcshapwrapper'(3 projects)
    .Configuration Manager
        .active solution platform
            .x86

With the best regards, c. Augusto
