### ISSUE TITLE
Question - any tool to help with the conversion?

### ISSUE THREAD

**Issue by govind-mukundan** [BoutemineOualid/WfdbCsharpWrapper#2]
Did you use any tool or utility for the conversion or did you have to manually create all the classes? I wish to write similar wrappers for some other C libraries and was wondering if there was an easy way to do it. 

Thanks for the libs, they have been very useful!

**Comment by BoutemineOualid** [comment]
Hi,

The WfdbCsharp Library was written from scratch. But there are several tools to generate bindings to native interfaces. You can check the C# wrapper available at the official physionet website. It was generated using swig.

**Comment by govind-mukundan** [comment]
Thanks for the quick reply! The "swig" project looks interesting!
